/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget105124;

import it.unicam.cs.pa.jbudget105124.View.GUIView.GUIViewStart;
import javafx.application.Application;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Application.launch(GUIViewStart.class);
        System.out.println(new App().getGreeting());
    }
}
