/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unicam.cs.pa.jbudget105124;

import it.unicam.cs.pa.jbudget105124.View.GUIView.GUIViewStart;
import javafx.application.Application;

/**
 * Classe da cui da cui parte il programma
 */
public class App {

    /**
     * Metodo main da cui viene lanciata la GUI View
     * @param args
     */
    public static void main(String[] args) {
        Application.launch(GUIViewStart.class);
    }
}
